### ISSUE TITLE
 single processor without parallel running

### ISSUE THREAD

**Issue by MiniSkull** [PanIGGCAS/SeisElastic2D_1.1#1]
Hi!
Thanks for sharing such great software!
I have one questions that confuses me a lot.
I am wondering whether I can run it with only one processor. 
Thanks,
Best regards,
Jin

**Comment by PanIGGCAS** [comment]
Hi Jin, 

I am sorry for missing your question. Running the forward modelling and inversion examples need at least 8 processors. If you want to run the codes with one processor, you need to change the parameter of "nproc" in Par_file to 1. You also need to re-generate the models and re-build the inversion example. Thanks very much for your attenuation and question.

 Wenyong

**Comment by MiniSkull** [comment]
Dear Dr.  Pan,

Thanks for answering my questions.
Now SeisElastic2D is running well.
I am trying to get familiar with it since it's a quite complex software.

Best regards,
Jin

________________________________

**Comment by PanIGGCAS** [comment]
> Dear Dr. Pan, Thanks for answering my questions. Now SeisElastic2D is running well. I am trying to get familiar with it since it's a quite complex software. Best regards, Jin
> […](#)
> ________________________________ From: Wenyong Pan <notifications@github.com> Sent: Wednesday, November 11, 2020 12:36 PM To: PanIGGCAS/SeisElastic2D_1.1 <SeisElastic2D_1.1@noreply.github.com> Cc: MiniSkull <jin.alex.wu@hotmail.com>; Author <author@noreply.github.com> Subject: Re: [PanIGGCAS/SeisElastic2D_1.1] single processor without parallel running (#1) Hi Jin, I am sorry for missing your question. Running the forward modelling and inversion examples need at least 8 processors. If you want to run the codes with one processor, you need to change the parameter of "nproc" in Par_file to 1. You also need to re-generate the models and re-build the inversion example. Thanks very much for your attenuation and question. Wenyong — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub<https://eur06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPanIGGCAS%2FSeisElastic2D_1.1%2Fissues%2F1%23issuecomment-725129848&data=04%7C01%7C%7C079c62011d0c45eef29308d885f2f830%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637406625872559386%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=obtTS%2FdSNdQ2vCXNQ3KVKYbTOqDT%2FM2fSIynjHlFaWw%3D&reserved=0>, or unsubscribe<https://eur06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAF7LIJA6SV5YTITB475FKALSPIBDTANCNFSM4TFURZ6A&data=04%7C01%7C%7C079c62011d0c45eef29308d885f2f830%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637406625872559386%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=mpNbRJWlxegZZ%2B556gqaWUWGDyklhx%2BFBe%2F5UfXPwkw%3D&reserved=0>.

Hi Jin,

I am very happy to know that it works well. It is indeed very complex and difficult to use at the beginning. Many forward modelling and FWI parameters need to be set for a successful application. After you are familiar with it, your research progress will be accelerated a lot. For any question, please feel free to contact me.

regards,

wenyong
